### ISSUE TITLE
Site can’t be reached

### ISSUE THREAD

**Issue by jmargutt** [IFRCGo/DREF-NLP#1]
Hello! I was trying to test your apps using the URLs
https://dref-pdf-parsing.azurewebsites.net/docs
https://dreftagging.azurewebsites.net/docs
https://dref-ptag.azurewebsites.net/docs
but they are not active, is the service disabled? Or has it been moved somewhere else?

**Comment by ypyelab** [comment]
Hi @jmargutt! Sorry for the late reply. We are actively using 'https://dreftagging.azurewebsites.net/classify', can you please check again? 

```
example = 'Security was a challenge especially during the distribution of hygiene packs as adjacent communities felt theyalso needed to benefit from relief items as they are equally vulnerable. Engagement of community leaders toexplain the rational of the operation diffused the tension.'
txt = ('"'+your_string_ready_to_classify+'"').encode('utf8')
req = requests.post('https://dreftagging.azurewebsites.net/classify', txt)
```

Was that classifier you were interested in? or in the extraction from the dref final reports?

**Comment by jmargutt** [comment]
both, but thanks, pls keep the readme up to date!
