### ISSUE TITLE
DREF-NLP does not find related appeal PDF-s

### ISSUE THREAD

**Issue by szabozoltan69** [IFRCGo/DREF-NLP#2]
On https://drefnlpdev.azurewebsites.net/docs#/default/parse_and_tag_parse_and_tag__output_format__post it is impossible to find existing appeal PDF-s, even with the built-in example string (MDRDO013): _"PDF URL for Appeal code MDRDO013 was not found using IFRC GO API call appeal_document"_. I tried it with the newest ones (e.g. MDRAR020), but still does not work.

Some appeal/appealdocument coupling or other ID-links or other API search possibilities might have been changed in the past few months.

Maybe https://github.com/IFRCGo/DREF-NLP/blob/master/dref_parsing/dref_parsing/parser_utils.py#L20 or https://github.com/IFRCGo/DREF-NLP/blob/master/dref_parsing/dref_parsing/parser_utils.py#L230 is obsolate in some sense?

@thenav56 any ideas?

**Comment by szabozoltan69** [comment]
I discovered that a point the DREF-parser uses such a request:
.../api/v2/appeal_document/?format=json&limit=300000
Which is quite resource intensive, not mentioning the 7-8 seconds while it runs.
(There is also a .../api/v2/appeal/?format=json&limit=300000 request which is a bit faster, but also quite resource intensive.)

**Comment by thenav56** [comment]
Hey @szabozoltan69 Looks like the API endpoint from go was changed. We will need to update the codebase here according to it.

We need to update the merged part to use the object field-value.
```diff
-    merged = aadf.merge(apdo, left_on='id', right_on='appeal')
+    merged = aadf.merge(apdo, left_on=aadf['id'].astype(int), right_on=apdo.appeal.str['id'])
```

Here is a working example.
```python
import requests
import pandas as pd

def download_api_results(call='appeal'):
    href = "https://goadmin.ifrc.org/api/v2/"+call+"/?format=json&limit=300000"
    aa = requests.get(href).json()
    return pd.DataFrame(aa['results'])

DREF_Final_Report_names = [
    'DREF Operation Final Report',
    'DREF Final Report',
    'DREF Operation Final Report 1'
]

# Filter only relevant DREF reports. Ignore case. 
def filter_DREF_Final_Reports(df, names=DREF_Final_Report_names):
    names_lower = [name.lower() for name in names]
    return df[df.name.apply(lambda x: x.lower() in names_lower)].copy().reset_index(drop=True)


appeal_df = download_api_results(call='appeal')
raw_apdo = download_api_results(call='appeal_document')
apdo = filter_DREF_Final_Reports(raw_apdo)

merged = appeal_df.merge(apdo, left_on=appeal_df['id'].astype(int), right_on=apdo.appeal.str['id'])

def find(lead):
    url_list = merged[merged.code==lead].document_url
    if not url_list.empty:
        return url_list.values[0]

print(merged.code)
print(find('MDRGH018'))
```

**Comment by szabozoltan69** [comment]
Many thanks, @thenav56 ! Great catch and elegant solution (to fix the merge of an id and a dictionary).

**Comment by szabozoltan69** [comment]
Recently I get this runtime error:
```
(Pdb) p aadf.merge(apdo, left_on=aadf['id'].astype(int), right_on=apdo.appeal.str['id'])
*** pandas.errors.IntCastingNaNError: Cannot convert non-finite values (NA or inf) to integer
```
[These](https://porgeto.hu/tmp/aadf_apdo.html) are the merged entities.

**Comment by szabozoltan69** [comment]
Hi @thenav56, I tried to solve this ^ issue via some "fillna(value=0)", but dit not help. :-(

**Comment by thenav56** [comment]
Hey @szabozoltan69 , We need to remove this line as well.
https://github.com/IFRCGo/DREF-NLP/blob/master/dref_parsing/dref_parsing/parser_utils.py#L267
```diff
-         apdo.appeal = apdo.appeal.astype(str)
```

**Comment by szabozoltan69** [comment]
Thanks so much @thenav56!
Now it works fine.

![kép](https://github.com/IFRCGo/DREF-NLP/assets/6050643/0aacfdbd-c9de-4370-af5e-56b470fee052)
@ypyelab
